# Generated by Django 2.1.7 on 2019-04-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190410_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='is_favorite',
        ),
    ]
