# Generated by Django 2.1.7 on 2019-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mix_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='directions',
            field=models.CharField(max_length=1000),
        ),
    ]
