# Generated by Django 2.1.7 on 2019-05-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190502_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
