# Generated by Django 2.1.7 on 2019-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
